jobs:
- job: Build
  timeoutInMinutes: 10
  pool:
    vmImage: ubuntu-latest

  steps:
  - checkout: self
    submodules: true
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3'

  - task: PipAuthenticate@0
    inputs:
      artifactFeeds: 'pros-cli'

  - script: ./scripts/build.sh
    displayName: 'Build Documentation'
  - task: CmdLine@2
    inputs:
      script: 'cp -r pros-doxygen-docs/ ./v5/pros-4'
  - task: PublishPipelineArtifact@0
    inputs:
      targetPath: artifacts
      artifactName: pros-docs.tar.gz
    displayName: Upload pros-docs.tar.gz
    condition: succeeded()
